v: 2.6.0
overrideConfig: q
ie:
    - DS_Store
    - less
    - scss
id:
    - scss
    - .svn
    - .sass-cache
cleanPublic: 'false'
patternStates:
    - inprogress
    - inreview
    - complete
styleGuideExcludes: 'templates,pages'
cacheBusterOn: 'true'
exportDir: export
publicDir: public
sourceDir: source
defaultPattern: all
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
    - hay
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
lineageMatch: '{%([ ]+)?(?:include|extends|embed)( |\()[&quot;\&#039;]([\/.@A-Za-z0-9-_]+)[&quot;\&#039;]([\s\S+]*?)%}'
lineageMatchKey: 3
patternExtension: twig
twigDebug: false
twigAutoescape: html
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
plugins:
    dataInheritance:
        enabled: true
    twigNamespaces:
        recursive: true
        enabled: false
        namespaces: { pages: { paths: [source/_patterns/05-pages] }, templates: { paths: [source/_patterns/04-templates] }, organisms: { paths: [source/_patterns/03-organisms] }, atoms: { paths: [source/_patterns/01-atoms] }, molecules: { paths: [source/_patterns/02-molecules] } }
        roots: {  }
    dataTransform:
        enabled: true
        verbose: false
